# Generated by Django 3.2.19 on 2023-06-18 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
