# Generated by Django 3.2.19 on 2023-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderlineitem_book_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='book_quality',
            field=models.CharField(max_length=7),
        ),
    ]
