# Generated by Django 3.2.19 on 2023-06-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_quality'),
        ('checkout', '0006_alter_orderlineitem_book_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='book_quality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.quality'),
        ),
    ]
