# Generated by Django 3.2.19 on 2023-07-01 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averagerating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, editable=False, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
