# Generated by Django 3.2.19 on 2023-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230701_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
