# Generated by Django 3.2.19 on 2023-07-03 15:50

from django.db import migrations


def add_qualities(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Quality = apps.get_model('products', 'Quality')

    for product in Product.objects.all():
        Quality.objects.create(product=product, name='Fair', price_factor=0.6)
        Quality.objects.create(product=product, name='Good', price_factor=0.8)
        Quality.objects.create(product=product, name='Great', price_factor=1.0)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bookreview_content'),
    ]

    operations = [
        migrations.RunPython(add_qualities),
    ]
