# Generated by Django 3.2.19 on 2023-06-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230604_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Great', 'Great')], default='Great', max_length=10),
        ),
        migrations.CreateModel(
            name='QualityVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.quality')),
            ],
        ),
    ]
