# Generated by Django 3.2.19 on 2023-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230606_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name_plural': 'Qualities'},
        ),
        migrations.AlterModelOptions(
            name='qualityvariants',
            options={'verbose_name_plural': 'Variants'},
        ),
        migrations.RemoveField(
            model_name='quality',
            name='price',
        ),
        migrations.AddField(
            model_name='quality',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
