# Generated by Django 3.2.19 on 2023-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230606_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityvariants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='qualityvariants',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('fair', 'Fair'), ('good', 'Good'), ('great', 'Great')], default='Great', max_length=10),
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='QualityVariants',
        ),
    ]
