# Generated by Django 3.2.19 on 2023-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230608_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='stars',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=3),
        ),
    ]
