# Generated by Django 3.2.19 on 2023-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='stars',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
    ]
