# Generated by Django 3.2.19 on 2023-06-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_bookreview_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='average_rating',
            new_name='averagerating',
        ),
    ]
